name: Buildable
# Try build, upload, and download a PYPI distribution.
# The dist is discarded.
on:
  workflow_dispatch:

jobs:
  builddist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Build dist
      run: |
        python -m pip install build --user
        python -m pip install twine --user
        python -m build
        twine check dist/*

    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist-rehersal
        path: dist/*
        retention-days: 5

  downloaddist:
    needs: builddist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist-rehersal
        path: dist
