name: CI

on:
  push:
  pull_request:
    branches: [develop]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install check-manifest
        pip install build
        pip install twine

    - name: Deployable
      run: |
        check-manifest -v
        python -m build
        python -m pip hash dist/*
        twine check dist/*

    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*
        retention-days: 5
