name: CI_README
# Run README.md examples on supported Python versions.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/publish.yml'
      - '.github/workflows/wheel.yml'

jobs:
  # Create unittest and doctest testfiles from README.md and upload.
  # This job runs on Python > 3.7 since phmutest does not support Python 3.7.
  generate_testfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install phmutest
        pip freeze
    - name: Generate testfiles
      run: |
        phmutest README.md --generate doc/generated_test_readme.py
        phmutest README.md --generate doc/generated_test_readme.txt --replmode
    - name: Upload testfiles
      uses: actions/upload-artifact@v4
      with:
        name: readme-artifact
        path: doc/generated_test_readme.*
        retention-days: 5

  # Dowwnload and run the unittest and doctest testfiles generated
  # from README.md on Python 3.7.
  # Running these examples is needed for code coverage.
  # Running ci.yml shows that coverage is 100%, but only
  # for Python 3.x.
  # We need to know none of the README.md examples break in Python 3.7.
  # We will assume they will still work in Python > 3.7 up to 3.x.
  run_testfiles:
    needs: generate_testfiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - uses: actions/download-artifact@v4
      with:
        name: readme-artifact
        path: testfiles
    - name: Show testfiles
      run: ls -l testfiles
    - name: Run testfiles
      run: |
        python -m unittest readme.py -vv
        python -m doctest readme.txt -vv
      working-directory: testfiles
