name: Build Dist
# todo- uncomment # todo- restore    pip install -r test/requirements.txt
# Important Note- monotable tests are in folder called "test".
on:
  push:
  #workflow_dispatch:
env:
  repos: tmarktaylor/monotable
  ref: v3.1.0

jobs:
  buildwheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ env.repos }}
        ref: ${{ env.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        python -m pip --version
        pip install build wheel
        pip freeze
    - name: Build dist
      run: |
        python -m build --no-isolation
        pip freeze
        pip hash dist/*
    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ env.ref }}
        path: dist/*
        retention-days: 5

  testwheel:
    runs-on: ubuntu-latest
    needs: buildwheel
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ env.repos }}
        ref: ${{ env.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Download dist
      uses: actions/download-artifact@v3
      with:
        name: dist-${{ env.ref }}
        path: dist
    - name: Install/test dist
      run: |
        # Delete the sources to prove we are testing the installed wheel.
        rm -fr monotable
        rm -f dist/*.gz
        python -m pip install --upgrade pip
        python -m pip --version
        pip hash dist/*
        pip install --no-index --find-links=dist monotable
        pip freeze
        # manually install test requirements since not currently in ref v3.1.0
        pip install pytest
        # todo- restore    pip install -r test/requirements.txt
        pip freeze
        pytest -vv test
