name: Build Dist
# todo- ref is specified in two places. (see ref: v3.1.0).
# todo- uncomment workflow_dispatch
# Important Note- monotable tests are in folder called "test".
#on:
#  workflow_dispatch:
on:
  push:

jobs:
  buildwheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: tmarktaylor/monotable
        ref: v3.1.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip freeze
    - name: Build dist
      run: |
        python -m build --no-isolation
        pip hash dist/*
        pip freeze
    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*
        retention-days: 5

  testwheel:
    runs-on: ubuntu-latest
    needs: buildwheel
    steps:
    - uses: actions/checkout@v2
      with:
        repository: tmarktaylor/monotable
        ref: v3.1.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Download dist
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Install/test dist
      run: |
        pip install --no-index --find-links=dist monotable
        pip freeze
        pip install -r test/requirements.txt
        pip freeze
        pytest -vv test
