name: Deploy to PYPI

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: tmarktaylor/monotable
        ref: v3.1.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build dist
      run: |
        python -m build
        pip hash dist/*
    - name: Install/test dist
      run: |
        pip install --no-index --find-links=dist monotable
        pip install -r test/requirements.txt
        pip freeze
        pytest -vv test

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        print_hash: true

    #- name: Publish to PyPI
    #  uses: pypa/gh-action-pypi-publish@release/v1
    #  with:
    #    user: __token__
    #    password: ${{ secrets.PYPI_API_TOKEN }}
    #    print_hash: true

    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*
        retention-days: 5
