name: Publish to PYPI

on:
  # Developers: If making changes here, also suggest adding a
  # github environment and add it to gh-action-pypi-publish below.
  workflow_dispatch:

env:
  ref: v3.1.0

jobs:
  builddist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.ref }}

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Build dist
      run: |
        python -m pip install build --user
        python -m build
        python -m pip hash dist/*

    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ env.ref }}
        path: dist/*
        retention-days: 5

  publish-pypi:
    needs: builddist
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT this permission is mandatory for trusted publishing
      id-token: write
    steps:

    - uses: actions/download-artifact@v3
      with:
        name: dist-${{ env.ref }}
        path: dist

    - name: Publish to Test PYPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        print-hash: true

    - name: Publish to PYPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
