name: Install from PYPI

on:
  workflow_dispatch:

env:
  project: monotable
  version: 3.1.0

jobs:
  pypi-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: PIP Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install "${{ env.project }}==${{ env.version }}"
        python -c "import ${{ env.project }}; print(${{ env.project }}.__version__)"
